### PR TITLE
US7369 - Input Group Button

### PR DESCRIPTION
**Pull request by seancdavis**
As a designer/developer, I want to see guidance for input-group-btn in the DDK & crds-styles. 

Note: Ties to crdschurch/crds-styleguide#94

---

Made this change to account for text being in the button, not just an icon. I didn't like assuming the icon didn't have a specific line height. I also wasn't a huge fan of using `button` selector instead of `.btn`, so that other button types can work here, too.

Feel free to argue my changes, @zarahzachz.

### CODE REVIEW

**Comment by seancdavis** [comment]
@tcmacdonald: I did have to adjust this slightly. The original styles were built for only an icon at its inherited line height. I set it explicitly and this is what I see:

screen shot 2017-04-05 at 7 52 47 am

Is your local crds-styleguide using the `feature/US7369-input-group-btn` branch of crds-styles?

**Comment by zarahzachz** [comment]
@seancdavis @tcmacdonald I just spun DDK up with the updated styles and the positioning of the button text/icon look fine to me. 

However, I do think there needs to be some distinction between a search bar and a styled input with connected button. The search bar will not have validation associated with it, whereas a submit field might. So I'd either add some documentation about this expected behaviour, or split the two examples up into separate sections (maybe making the search bar a molecule component?).

**Comment by seancdavis** [comment]
Yes, good points, @zarahzachz. I do have [another PR](https://github.com/crdschurch/crds-styleguide/pull/95) that is focused on the search piece separately. Here I was just showing that both an icon and text will work in the button.

**Comment by seancdavis** [comment]
@tcmacdonald: I set the height explicitly on both the input and the button and they are looking better for me. Let me know what you think.

**Pull request merged**
